name: liferay-workspace-testing
services:
    liferay:
        container_name: liferay-workspace-testing-liferay-portal
        healthcheck:
            interval: 5s
            start_period: 3m
            test: "/opt/liferay/health-check.sh"
            timeout: 10m
        image: liferay-workspace-testing-liferay:2024.q3.7
        network_mode: host
        volumes:
            - routes:/opt/liferay/routes
    microservice-node:
        container_name: liferay-workspace-testing-microservice-node
        depends_on:
            liferay:
                condition: service_healthy
        environment:
            - LIFERAY_ROUTES_CLIENT_EXTENSION=/etc/liferay/routes/default/liferay-sample-etc-node
            - LIFERAY_ROUTES_DXP=/etc/liferay/routes/default/dxp
        healthcheck:
            test: curl localhost:3001
        image: liferay-sample-etc-node:latest
        network_mode: host
        restart: unless-stopped
        volumes:
            - routes:/etc/liferay/routes
    microservice-spring-boot:
        container_name: liferay-workspace-testing-microservice-spring-boot
        depends_on:
            liferay:
                condition: service_healthy
        environment:
            - LIFERAY_ROUTES_CLIENT_EXTENSION=/etc/liferay/routes/default/liferay-sample-etc-spring-boot
            - LIFERAY_ROUTES_DXP=/etc/liferay/routes/default/dxp
        healthcheck:
            test: curl localhost:58081
        image: liferay-sample-etc-spring-boot:latest
        network_mode: host
        restart: unless-stopped
        volumes:
            - routes:/etc/liferay/routes
volumes:
    routes: